#!/usr/bin/env python3
"""
load_customers_to_supabase.py

One-shot import of office_customers.json (generated by load_customers.py)
into Supabase public.customers. Idempotent: upserts by customer_code.

Usage:
    python3 load_customers_to_supabase.py
    python3 load_customers_to_supabase.py --input path/to/customers.json

Required env:
    SUPABASE_URL=https://xxx.supabase.co
    SUPABASE_SERVICE_ROLE_KEY=eyJ...

Reads SERVICE_ROLE_KEY from ~/.hermes/.env if not in env. Uses the service
role key (NOT anon key) because customers table RLS only allows service-role
writes.

After import: run migration 20260808_customer_emails.sql to backfill the
customer_emails table from customers.email (multi-email parsing handled
in the SQL with regexp_split_to_array).
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import urllib.request
import urllib.error


SUPABASE_URL = os.environ.get('SUPABASE_URL', 'https://ruwyfesblmaurfuiaofw.supabase.co')

DEFAULT_INPUT = Path('/Users/tfross/.hermes/nativesons-order/office_customers.json')


def get_service_key() -> str:
    """Read SUPABASE_SERVICE_ROLE_KEY from env or ~/.hermes/.env."""
    key = os.environ.get('SUPABASE_SERVICE_ROLE_KEY')
    if key:
        return key
    env_path = Path.home() / '.hermes' / '.env'
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line.startswith('SUPABASE_SERVICE_ROLE_KEY='):
                val = line.split('=', 1)[1].strip().strip('"').strip("'")
                if val:
                    return val
    sys.exit('SUPABASE_SERVICE_ROLE_KEY not set and not found in ~/.hermes/.env')


def upsert_batch(url: str, headers: dict, rows: list, batch_num: int) -> tuple:
    """Upsert a batch of customer rows. Returns (success_count, error_count)."""
    body = json.dumps(rows).encode('utf-8')
    req = urllib.request.Request(
        f'{url}/rest/v1/customers',
        data=body,
        headers={**headers, 'Content-Type': 'application/json',
                 'Prefer': 'resolution=merge-duplicates,return=minimal'},
        method='POST',
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return (len(rows), 0) if resp.status in (200, 201, 204) else (0, len(rows))
    except urllib.error.HTTPError as e:
        body_text = e.read().decode('utf-8', errors='replace')[:500]
        print(f'  Batch {batch_num} failed: HTTP {e.code}: {body_text}')
        return (0, len(rows))
    except Exception as e:
        print(f'  Batch {batch_num} failed: {type(e).__name__}: {e}')
        return (0, len(rows))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--input', type=Path, default=DEFAULT_INPUT,
                    help='Path to office_customers.json')
    ap.add_argument('--batch-size', type=int, default=200)
    ap.add_argument('--dry-run', action='store_true',
                    help='Parse and show counts without uploading')
    args = ap.parse_args()

    if not args.input.exists():
        sys.exit(f'Input not found: {args.input}')

    print(f'Loading {args.input}')
    customers = json.loads(args.input.read_text())
    print(f'Loaded {len(customers)} customer records')

    # Stats
    with_email = sum(1 for c in customers if c.get('email'))
    multi_email = sum(1 for c in customers
                      if c.get('email') and any(s in c['email'] for s in [',', ';', '\n']))
    print(f'  with email: {with_email}')
    print(f'  multi-email (sep-separated): {multi_email}')

    if args.dry_run:
        print('\nDry run — skipping upload')
        # Show 3 sample multi-email customers so we can verify parsing logic
        print('\nSample multi-email customers:')
        shown = 0
        for c in customers:
            if c.get('email') and any(s in c['email'] for s in [',', ';', '\n']):
                print(f'  {c["customer_code"]:<12} {c["name"][:50]}')
                print(f'    raw email: {c["email"][:160]}')
                shown += 1
                if shown >= 5:
                    break
        return

    url = SUPABASE_URL
    key = get_service_key()
    headers = {
        'apikey': key,
        'Authorization': f'Bearer {key}',
    }

    # Normalize rows to match Supabase column names
    rows = []
    skipped = 0
    for c in customers:
        if not c.get('customer_code') and not c.get('name'):
            skipped += 1
            continue
        row = {
            'customer_code': c.get('customer_code') or None,
            'name': c.get('name') or '',
            'contact_name': c.get('contact_name') or None,
            'address': c.get('address') or None,
            'city': c.get('city') or None,
            'state': c.get('state') or None,
            'zip': c.get('zip') or None,
            'email': c.get('email') or None,
            'phone': c.get('phone') or None,
            'discount': c.get('discount') or None,
            'default_markup_pct': c.get('default_markup_pct'),
            'resale_no': c.get('resale_no') or None,
            'routing': c.get('routing') or None,
            'sales_person': c.get('sales_person') or None,
            'sales_tax_pct': c.get('sales_tax_pct'),
            'terms': c.get('terms') or None,
            'type': c.get('type') or None,
            'website': c.get('website') or None,
            'ship_to_name': c.get('ship_to_name') or None,
            'ship_to_address': c.get('ship_to_address') or None,
            'ship_to_city': c.get('ship_to_city') or None,
            'ship_to_state': c.get('ship_to_state') or None,
            'ship_to_zip': c.get('ship_to_zip') or None,
            'ship_via': c.get('ship_via') or None,
            'shipping_charge': c.get('shipping_charge'),
            'comment': c.get('comment') or None,
            'search_text': c.get('search_text') or None,
            # Mark active=true by default; preserves existing rows that already had it set
            'active': c.get('active', True),
        }
        rows.append(row)

    print(f'Uploading {len(rows)} rows in batches of {args.batch_size} (skipped {skipped})')

    total_ok = 0
    total_err = 0
    started = time.time()
    for i in range(0, len(rows), args.batch_size):
        batch = rows[i:i + args.batch_size]
        batch_num = (i // args.batch_size) + 1
        ok, err = upsert_batch(url, headers, batch, batch_num)
        total_ok += ok
        total_err += err
        if batch_num % 10 == 0 or batch_num == 1:
            elapsed = time.time() - started
            print(f'  Batch {batch_num}: {ok} ok / {err} err ({elapsed:.1f}s elapsed)')

    print(f'\nDone: {total_ok} uploaded, {total_err} failed in {time.time() - started:.1f}s')
    if total_err == 0:
        print('\nNext step: run supabase/migrations/20260808_customer_emails.sql in the SQL editor.')
        print('That migration creates customer_emails and backfills from customers.email (multi-email parsing).')
    else:
        print(f'\n{total_err} rows failed. Re-run the script — only failed rows will be retried (upsert is idempotent).')


if __name__ == '__main__':
    main()
