#!/usr/bin/env python3
"""refresh_sales_data.py — regenerate sales-portal JSONs from FileMaker CSV.

Reads the FileMaker export at /Users/tfross/Sync/Orders_Tim/nssalesdata.csv
and produces four JSON files in the repo root that the sales portal pages
load as static assets:

  aug2026_sales.json     — sales_dashboard.html — current-month rollup
  rep_annual_2025_2026.json — rep_annual_2025_2026.html — rep/year matrix
  rep_monthly_2026.json  — rep_monthly_2026.html — rep/month matrix
  trends_data.json       — trends.html + sales_dashboard.html — ytd + weekly

Usage:
  python3 scripts/refresh_sales_data.py                    # default paths
  python3 scripts/refresh_sales_data.py --csv PATH --out-dir PATH
  python3 scripts/refresh_sales_data.py --dry-run         # print, don't write

Why this script exists (commit log):
  The JSONs were originally generated by a one-off script run on Tim's
  laptop. When the FileMaker CSV updated (Aug 26, 2026), the JSONs went
  stale and the sales portal started showing the wrong numbers. This
  script lives in the repo so any future refresh is a single command.

CSV column layout (verified 2026-08-31 from /Users/tfross/Sync/Orders_Tim/nssalesdata.csv):

  0  Bill To               — customer name (denormalized)
  4  Order Total           — *per-invoice revenue* (the canonical number)
  17 InvoiceNo             — integer
  18 Item Number           — NS item code (matches plantmasteritem)
  26 Quantity Ordered      — int
  28 Sales Person          — rep name as-written (no normalization)
  40 Size                  — container (4in / 1gal / etc.)
  50 Clients::Customer Number — customer code (matches existing JSON)

Reps in the source are spelled inconsistently ("Tim" vs "Tim (CR)",
"Book" vs "In-House"). We strip parenthetical suffixes for the
canonical name and keep the suffix as a "credit memo" flag.

Important — GrandTotal vs Order Total:
  - 'GrandTotal' is the CUSTOMER LIFETIME running total across all
    of their orders (constant across line items, ~$39M per customer).
    Do NOT use it for per-invoice revenue.
  - 'Order Total' is the per-invoice revenue (one number per invoice,
    repeated across line items of the same invoice). Use this.
  Verified 2026-08-31: existing aug2026_sales.json invoice 166790
  total is 1568.56, which matches CSV Order Total for invoice 166790.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import defaultdict
from datetime import date, datetime, timedelta
from pathlib import Path

DEFAULT_CSV = Path('/Users/tfross/Sync/Orders_Tim/nssalesdata.csv')
DEFAULT_OUT = Path(__file__).resolve().parent.parent  # repo root

# CSV column names (use the actual headers, not indices — DictReader handles lookup)
COL_BILL_TO = 'Bill To'
COL_GRAND = 'GrandTotal'  # NOT USED — customer lifetime running total, see top-of-file comment
COL_ORDER_TOTAL = 'Order Total'  # per-invoice revenue
COL_DATE = 'Order Date'
COL_INVOICE = 'InvoiceNo'
COL_ITEM = 'Item Number'
COL_QTY = 'Quantity Ordered'
COL_REP = 'Sales Person'
COL_SIZE = 'Size'
COL_UNIT = 'Unit Price'
COL_CUST_NUM = 'Clients::Customer Number'
COL_DESC = 'Description'


def parse_csv(csv_path: Path):
    """Stream the CSV once, yielding one row per line item. Yields dicts
    with the columns we actually use, with safe type coercion. Bad rows
    (missing invoice/date/order-total) are skipped with a counter."""
    with open(csv_path, encoding='utf-8', errors='replace', newline='') as f:
        reader = csv.DictReader(f)
        skipped = 0
        n = 0
        for row in reader:
            n += 1
            try:
                invoice = (row.get(COL_INVOICE) or '').strip()
                date_s = (row.get(COL_DATE) or '').strip()[:10]
                order_total = float(row.get(COL_ORDER_TOTAL) or '0')
            except (ValueError, AttributeError):
                skipped += 1
                continue
            if not invoice or not date_s or order_total <= 0:
                skipped += 1
                continue
            yield {
                'invoice': invoice,
                'date': date_s,
                'total': order_total,
                'rep': (row.get(COL_REP) or '').strip(),
                'customer_code': (row.get(COL_CUST_NUM) or '').strip(),
                'customer_name': (row.get(COL_BILL_TO) or '').strip(),
                'item_code': (row.get(COL_ITEM) or '').strip(),
                'description': (row.get(COL_DESC) or '').strip(),
                'size': (row.get(COL_SIZE) or '').strip(),
                'qty': int(row.get(COL_QTY) or '1'),
                'unit_price': float(row.get(COL_UNIT) or '0'),
            }
        if skipped:
            print(f'  (skipped {skipped}/{n} rows missing invoice/date/total)',
                  file=sys.stderr)


def aggregate_orders(rows):
    """Group line items into per-invoice orders. The CSV is line-item
    level, but the JSONs are order-level (each InvoiceNo once). One
    invoice can have multiple line items, all sharing the same date /
    rep / customer / Order Total (CSV has Order Total denormalized
    across line items, so we use the first non-zero value seen)."""
    orders = {}
    for r in rows:
        inv = r['invoice']
        if inv not in orders:
            orders[inv] = {
                'invoice': inv,
                'date': r['date'],
                'total': r['total'],
                'rep': r['rep'],
                'customer_code': r['customer_code'],
                'customer_name': r['customer_name'],
                'lines': 0,
            }
        orders[inv]['lines'] += 1
    return sorted(orders.values(), key=lambda o: (o['date'], o['invoice']), reverse=True)


def normalize_rep(name):
    """Strip '(CR)' credit-memo suffix from a rep name so the canonical
    name matches the one shown elsewhere on the portal. E.g. 'Tim (CR)'
    becomes 'Tim'. Empty names stay empty."""
    if not name:
        return ''
    return re.sub(r'\s*\([A-Z]+\)\s*$', '', name).strip()


def build_aug2026_sales(orders, source_csv: Path):
    """current-month rollup: orders in the latest month in the CSV, plus
    daily/rep/customer rollups for that month."""
    if not orders:
        return {'meta': {'generated_at': '', 'source': str(source_csv), 'period': '', 'n_orders': 0, 'total_revenue': 0.0}, 'orders': [], 'daily': [], 'by_rep': [], 'top_customers': []}
    months = sorted({o['date'][:7] for o in orders}, reverse=True)
    latest_month = months[0]
    month_orders = [o for o in orders if o['date'].startswith(latest_month)]
    period_label = datetime.strptime(latest_month + '-01', '%Y-%m-%d').strftime('%B %Y')

    daily = defaultdict(lambda: {'revenue': 0.0, 'orders': 0})
    for o in month_orders:
        d = daily[o['date']]
        d['revenue'] += o['total']
        d['orders'] += 1
    daily_list = [{'date': d, 'revenue': round(v['revenue'], 2), 'orders': v['orders']}
                  for d, v in sorted(daily.items())]

    by_rep = defaultdict(lambda: {'revenue': 0.0, 'orders': 0})
    for o in month_orders:
        rep = normalize_rep(o['rep']) or '(unknown)'
        r = by_rep[rep]
        r['revenue'] += o['total']
        r['orders'] += 1
    by_rep_list = [{'rep': k, 'revenue': round(v['revenue'], 2), 'orders': v['orders']}
                   for k, v in sorted(by_rep.items(), key=lambda kv: -kv[1]['revenue'])]

    by_cust = defaultdict(lambda: {'revenue': 0.0, 'orders': 0})
    for o in month_orders:
        if not o['customer_code']:
            continue
        c = by_cust[o['customer_code']]
        c['revenue'] += o['total']
        c['orders'] += 1
        c['name'] = o['customer_name']
    top_customers = [
        {
            'customer_code': k,
            'customer_name': v.get('name', k),
            'revenue': round(v['revenue'], 2),
            'orders': v['orders'],
        }
        for k, v in sorted(by_cust.items(), key=lambda kv: -kv[1]['revenue'])[:15]
    ]

    return {
        'meta': {
            'generated_at': datetime.now().isoformat(timespec='seconds'),
            'source': str(source_csv),
            'period': period_label,
            'n_orders': len(month_orders),
            'total_revenue': round(sum(o['total'] for o in month_orders), 2),
        },
        'orders': [{
            'invoice': o['invoice'],
            'date': o['date'],
            'total': round(o['total'], 2),
            'rep': normalize_rep(o['rep']),
            'customer_code': o['customer_code'],
            'customer_name': o['customer_name'],
        } for o in month_orders],
        'daily': daily_list,
        'by_rep': by_rep_list,
        'top_customers': top_customers,
    }


def build_rep_annual(orders):
    """rep/year matrix for rep_annual_2025_2026.html. Uses 2025 + 2026 YTD."""
    by_rep_year = defaultdict(lambda: defaultdict(lambda: {'revenue': 0.0, 'orders': 0}))
    for o in orders:
        year = o['date'][:4]
        if year not in ('2025', '2026'):
            continue
        rep = normalize_rep(o['rep']) or '(unknown)'
        r = by_rep_year[rep][year]
        r['revenue'] += o['total']
        r['orders'] += 1

    years = ['2025', '2026']
    rep_year = {}
    for rep in by_rep_year:
        rep_year[rep] = {
            y: {
                'revenue': round(by_rep_year[rep][y]['revenue'], 2),
                'orders': by_rep_year[rep][y]['orders'],
            } for y in years
        }

    year_totals = {}
    for y in years:
        rev = sum(by_rep_year[rep][y]['revenue'] for rep in by_rep_year)
        ords = sum(by_rep_year[rep][y]['orders'] for rep in by_rep_year)
        year_totals[y] = {'revenue': round(rev, 2), 'orders': ords}

    return {
        'meta': {
            'generated_at': datetime.now().isoformat(timespec='seconds'),
            'period': '2025 + 2026 YTD (Jan-Aug)',
        },
        'rep_year': rep_year,
        'year_totals': year_totals,
    }


def build_rep_monthly(orders):
    """rep/month matrix for rep_monthly_2026.html. Only 2026 orders."""
    months = sorted({o['date'][:7] for o in orders if o['date'].startswith('2026')})

    by_rep = defaultdict(lambda: {'revenue': 0.0, 'orders': 0,
                                  'monthly': defaultdict(lambda: {'revenue': 0.0, 'orders': 0})})
    for o in orders:
        if not o['date'].startswith('2026'):
            continue
        rep = normalize_rep(o['rep']) or '(unknown)'
        r = by_rep[rep]
        r['revenue'] += o['total']
        r['orders'] += 1
        m = o['date'][:7]
        mr = r['monthly'][m]
        mr['revenue'] += o['total']
        mr['orders'] += 1

    reps_list = []
    for rep in sorted(by_rep.keys()):
        r = by_rep[rep]
        monthly = {m: {
            'revenue': round(r['monthly'][m]['revenue'], 2),
            'orders': r['monthly'][m]['orders'],
        } for m in months}
        reps_list.append({
            'rep': rep,
            'ytd_revenue': round(r['revenue'], 2),
            'ytd_orders': r['orders'],
            'monthly': monthly,
        })

    month_totals = {}
    for m in months:
        rev = sum(by_rep[rep]['monthly'][m]['revenue'] for rep in by_rep)
        ords = sum(by_rep[rep]['monthly'][m]['orders'] for rep in by_rep)
        month_totals[m] = {'revenue': round(rev, 2), 'orders': ords}

    return {
        'meta': {
            'generated_at': datetime.now().isoformat(timespec='seconds'),
            'period': '2026 YTD',
        },
        'months': months,
        'reps': reps_list,
        'month_totals': month_totals,
    }


def build_trends(orders):
    """trends_data.json — YTD + last 12 weeks weekly rollup."""
    ytd_orders = [o for o in orders if o['date'].startswith('2026')]
    ytd_revenue = round(sum(o['total'] for o in ytd_orders), 2)
    ytd_n_orders = len(ytd_orders)
    ytd_customers = len({o['customer_code'] for o in ytd_orders if o['customer_code']})

    by_rep = defaultdict(lambda: {'revenue': 0.0, 'orders': 0, 'customers': set()})
    for o in ytd_orders:
        rep = normalize_rep(o['rep']) or '(unknown)'
        r = by_rep[rep]
        r['revenue'] += o['total']
        r['orders'] += 1
        if o['customer_code']:
            r['customers'].add(o['customer_code'])
    reps_list = []
    for rep in sorted(by_rep.keys(), key=lambda k: -by_rep[k]['revenue']):
        r = by_rep[rep]
        reps_list.append({
            'rep': rep,
            'revenue': round(r['revenue'], 2),
            'orders': r['orders'],
            'customers': len(r['customers']),
        })

    today = date.today()
    weeks = []
    for i in range(12):
        week_end = today - timedelta(days=7 * i)
        week_start = week_end - timedelta(days=6)
        weeks.append((week_start.isoformat(), week_end.isoformat()))
    weeks.reverse()

    weekly = []
    for wstart, wend in weeks:
        in_week = [o for o in orders if wstart <= o['date'] <= wend]
        rev = round(sum(o['total'] for o in in_week), 2)
        ords = len(in_week)
        weekly.append({'week_start': wstart, 'week_end': wend, 'revenue': rev, 'orders': ords})

    monthly = defaultdict(lambda: {'revenue': 0.0, 'orders': 0})
    for o in ytd_orders:
        m = o['date'][:7]
        monthly[m]['revenue'] += o['total']
        monthly[m]['orders'] += 1
    monthly_list = [{'month': m, 'revenue': round(v['revenue'], 2), 'orders': v['orders']}
                    for m, v in sorted(monthly.items())]

    last_year = str(int(today.year) - 1)
    yoy_orders = [o for o in orders if o['date'].startswith(last_year) and
                  o['date'][5:] <= today.strftime('%m-%d')]
    yoy = {
        'year': last_year,
        'revenue': round(sum(o['total'] for o in yoy_orders), 2),
        'orders': len(yoy_orders),
    } if yoy_orders else None

    return {
        'meta': {
            'generated_at': datetime.now().isoformat(timespec='seconds'),
            'source': str(DEFAULT_CSV),
            'period': '2026 YTD + Last 12 weeks',
        },
        'ytd': {
            'revenue': ytd_revenue,
            'orders': ytd_n_orders,
            'customers': ytd_customers,
            'reps': reps_list,
        },
        'weekly': weekly,
        'monthly': monthly_list,
        'yoy': yoy,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--csv', type=Path, default=DEFAULT_CSV, help=f'FileMaker CSV (default: {DEFAULT_CSV})')
    ap.add_argument('--out-dir', type=Path, default=DEFAULT_OUT, help=f'Output directory (default: repo root: {DEFAULT_OUT})')
    ap.add_argument('--dry-run', action='store_true', help='Print what would be written without writing')
    args = ap.parse_args()

    if not args.csv.exists():
        print(f'ERROR: CSV not found at {args.csv}', file=sys.stderr)
        sys.exit(1)

    print(f'Reading {args.csv}')
    rows = list(parse_csv(args.csv))
    print(f'  parsed {len(rows)} line items')

    orders = aggregate_orders(rows)
    print(f'  aggregated {len(orders)} unique invoices')

    builds = [
        ('aug2026_sales.json', build_aug2026_sales(orders, args.csv)),
        ('rep_annual_2025_2026.json', build_rep_annual(orders)),
        ('rep_monthly_2026.json', build_rep_monthly(orders)),
        ('trends_data.json', build_trends(orders)),
    ]

    for name, data in builds:
        path = args.out_dir / name
        if name == 'aug2026_sales.json':
            m = data['meta']
            print(f'  {name}: {m["period"]} — {m["n_orders"]} orders, ${m["total_revenue"]:,.2f}')
        elif name == 'rep_annual_2025_2026.json':
            print(f'  {name}: {data["meta"]["period"]} — {len(data["rep_year"])} reps')
        elif name == 'rep_monthly_2026.json':
            print(f'  {name}: {data["meta"]["period"]} — {len(data["months"])} months, {len(data["reps"])} reps')
        elif name == 'trends_data.json':
            m = data['meta']
            ytd = data['ytd']
            print(f'  {name}: {m["period"]} — YTD ${ytd["revenue"]:,.2f} / {ytd["orders"]} orders')
        if not args.dry_run:
            with open(path, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
                f.write('\n')
            print(f'    wrote {path} ({path.stat().st_size:,} bytes)')
        else:
            print(f'    (dry-run) would write {path}')


if __name__ == '__main__':
    main()
